services: 
  postgres:
    build:
      context: ./TestDependencies
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: "test-db"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      - "discovery.type=single-node"
    container_name: "elastic-test"
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "9000:9000"
    container_name: "clickhouse-test"
    
    
 


  
    
    